name: francessco_us
publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4
  eco:
    git: https://github.com/Francessco121/eco.git

dependency_overrides:
  eco:
    path: ../eco
