name: francessco_us
publish_to: none

environment:
  sdk: '>=2.5.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
  eco:
    git: https://github.com/Francessco121/eco.git
  sass_builder: ^2.1.3
  shelf_proxy: ^0.1.0

dependency_overrides:
  eco:
    path: ../../eco/eco