name: francessco_us
publish_to: none

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4
  eco:
    git: https://github.com/Francessco121/eco.git
  # TODO: Use pub version when they update their build dependency
  sass_builder:
    git:
      url: https://github.com/dart-league/sass_builder.git
      ref: e76da918cf27bf14e324b2343ff4f7ee38e98693

dependency_overrides:
  eco:
    path: ../eco
